#There are three requirements for building on Windows:
#
#    You must use a version of Rust which uses the MSVC toolchain
#    You must have WinPcap or npcap installed (tested with version WinPcap 4.1.3) (If using npcap, make sure to install with the "Install Npcap in WinPcap API-compatible Mode")
#    You must place Packet.lib from the WinPcap Developers pack in a directory named lib, in the root of this repository. Alternatively, you can use any of the locations listed in the %LIB%/$Env:LIB environment variables. For the 64 bit toolchain it is in WpdPack/Lib/x64/Packet.lib, for the 32 bit toolchain, it is in WpdPack/Lib/Packet.lib.
#./target/debug/main.exe --config ./src/config_example/tcp.toml
#./target/debug/main.exe --config ../../src/config_example/udp.toml
#./target/debug/main.exe --config ./src/config_example/udp.toml

mode = "tcp"
log_level = "info"
key="123a41313"
# optional

[config]
##only ip,//domain todo
target ="23.224.89.189"
##your network interface mac (can show in this software)
interface="44:af:28:a1:09:0f"
thread=4
count=0